# Vectorized Code Fundamentals

### Submitted by: Vatsalya Gupta, SC19B098, B.Tech. ECE VII Sem

In [1]:
import numpy as np

In [2]:
A = np.array([[-2, -3], [1, 0]])
B = np.array([[1, 1], [1, 0]])
x = np.array([[-1], [1]])

print(f"A =\n{A}")
print(f"B =\n{B}")
print(f"x =\n{x}")

A =
[[-2 -3]
 [ 1  0]]
B =
[[1 1]
 [1 0]]
x =
[[-1]
 [ 1]]


In [3]:
C = np.linalg.inv(A)
print(f"C = A^(-1) =\n{C}")

C = A^(-1) =
[[-0.          1.        ]
 [-0.33333333 -0.66666667]]


In [4]:
I1 = np.matmul(A, C)
I2 = np.matmul(C, A)
print(f"A.C =\n{I1}")
print(f"C.A =\n{I2}")

A.C =
[[ 1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00]]
C.A =
[[1. 0.]
 [0. 1.]]


In [5]:
Ax = np.matmul(A, x)
print(f"Ax =\n{Ax}")

Ax =
[[-1]
 [-1]]


In [6]:
ATA = np.matmul(np.transpose(A), A)
print(f"A^(T)A =\n{ATA}")

A^(T)A =
[[5 6]
 [6 9]]


In [7]:
ABT = np.transpose(np.matmul(A, B))
print(f"(AB)^T =\n{ABT}")

(AB)^T =
[[-5  1]
 [-2  1]]


In [8]:
Ax_Bx = Ax - np.matmul(B, x)
print(f"Ax - Bx =\n{Ax_Bx}")

Ax - Bx =
[[-1]
 [ 0]]


In [9]:
x_norm = np.linalg.norm(x)
print(f"||x|| =\n{x_norm}")

||x|| =
1.4142135623730951


In [10]:
Ax_Bx_norm = np.linalg.norm(Ax_Bx)
print(f"||Ax - Bx|| =\n{Ax_Bx_norm}")

||Ax - Bx|| =
1.0


In [11]:
print(f"First column of A =\n{A[:, 0]}")

First column of A =
[-2  1]


In [12]:
D = B.copy()
D[:, 0] = x[:, 0]
print(f"D =\n{D}")

D =
[[-1  1]
 [ 1  0]]


In [13]:
element_product = np.multiply(A[:, 0], A[:, 1])
print(f"Element-wise product between first and second columns of A =\n{element_product}")

Element-wise product between first and second columns of A =
[6 0]
